server:
  port: ${HTTP_PORT}
spring:
  application:
    name: currency-conversion
  config:
    import: optional:configserver:http://localhost:8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  tracing:
    sampling:
      probability: 1.0
#zipkin:tracing:endpoint:  -- for manage zipkin url
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
