server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/TarasVovk669/demo-config-server.git
logging:
  level:
    root: info

