version: '3.7'

services:
  currency-exchange:
    image: taras-vovk/micros-currency-conversion-service:0.0.1-SNAPSHOT
    mem_reservation: 700m
    ports:
      - "8000:8000"
    environment:
      - EUREKA.CLIENT.SERVICEURL.DEFAULTZONE=http://naming-service:8761/eureka
      - MANAGEMENT.ZIPKIN.TRACING.ENDPOINT=http://zipkin-server:9411/api/v2/spans
      - HTTP_PORT=8000
    networks:
      - currency-network
    depends_on:
      - naming-service
  currency-conversion:
    image: taras-vovk/micros-currency-conversion-service:0.0.1-SNAPSHOT
    mem_reservation: 700m
    ports:
      - "8100:8100"
    environment:
      - EUREKA.CLIENT.SERVICEURL.DEFAULTZONE=http://naming-service:8761/eureka
      - MANAGEMENT.ZIPKIN.TRACING.ENDPOINT=http://zipkin-server:9411/api/v2/spans
      - HTTP_PORT=8100
    networks:
      - currency-network
    depends_on:
      - naming-service
  api-gateway:
    image: taras-vovk/micros-api-gateway:0.0.1-SNAPSHOT
    mem_reservation: 700m
    ports:
      - "8765:8765"
    environment:
      - EUREKA.CLIENT.SERVICEURL.DEFAULTZONE=http://naming-service:8761/eureka
      - MANAGEMENT.ZIPKIN.TRACING.ENDPOINT=http://zipkin-server:9411/api/v2/spans
    networks:
      - currency-network
    depends_on:
      - naming-service
  zipkin-server:
    image: openzipkin/zipkin:2.23
    mem_reservation: 300m
    ports:
      - "9411:9411"
    networks:
      - currency-network
    restart: always #Restart if there is a problem starting up
  naming-service:
    image: taras-vovk/micros-naming-server:0.0.1-SNAPSHOT
    mem_reservation: 700m
    ports:
      - "8761:8761"
    networks:
      - currency-network
networks:
  currency-network: