spring:
  application:
    name: manager-service
  datasource:
    username: user123
    password: pass123
    url: jdbc:postgresql://localhost:5432/manager
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8083/realms/manager-app
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: manager-app
            client-secret: 64Y3G7Dqso8jlFUGsCnLXLahYcwLQWcK
            scope:
              - openid
              - view_catalogue
              - edit_catalogue
              - microprofile-jwt

  flyway:
    schemas:
      - public
      - user_management
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
server:
  port: 8081

manager-service:
  catalog-service:
    registration-id: keycloak
    url: http://localhost:8082
    username: user123
    password: pass123