spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: q1q2q3q4
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
logging:
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %clr([%X{correlation_id}]){green} %m%n%wEx'