server:
  port: 8086
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: q1q2q3q4
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  jackson:
    property-naming-strategy: SNAKE_CASE
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null

