server:
  port: ${HTTP_PORT}
spring:
  application:
    name: currency-exchange
  config:
    import: optional:configserver:http://localhost:8888
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:curr-serv-db
    username: sa
    password:
  h2:
    console:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
resilience4j:
  retry:
    instances:
      name-give-example:
        maxAttempts: 5
        waitDuration: 3s
        enable-exponential-backoff: true
  ratelimiter:
    instances:
      rate-circuit-limiter:
        limitForPeriod: 2
        limitRefreshPeriod: 10s
  bulkhead:
    instances:
      bulkhead-example:
        maxConcurrentCalls: 10




