
POST http://localhost:8081/jwt/tokens
Authorization: Basic dGFyYXNAZ21haWwuY29tOnBhc3MxMjM=

###
GET http://localhost:8081/public/manager.html
Authorization: Bearer eyJraWQiOiJjZTQ3YzUyYS0yN2QwLTRkMTktYjg3ZS03N2RlYjVmYmE5ZTUiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0YXJhc0BnbWFpbC5jb20iLCJleHAiOjE3MDkxMzY4NDUsImlhdCI6MTcwOTEzNjU0NSwianRpIjoiY2U0N2M1MmEtMjdkMC00ZDE5LWI4N2UtNzdkZWI1ZmJhOWU1IiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9NQU5BR0VSIiwiUk9MRV9VU0VSIl19.srUyLZHzcBf-Px6kQiSDjkZRaA7fuzpqncw391titvI

###
POST http://localhost:8081/jwt/refresh
Authorization: Bearer eyJraWQiOiI2NjIwZWY4My02ZmNmLTQwMzItYjk0OC1mM2Y2NjI0N2UwOTMiLCJlbmMiOiJBMTI4R0NNIiwiYWxnIjoiZGlyIn0..MT3gwJhRXL_fw8Ki.EF4CbcID5dlD2S_gJYS1_fUDzqDOa3tUTmN2y63qGWbqQ4RHjjKEcB3UTMurzYXWdUzJaDZzRGI0ADxTpawIZRDyAd7_XkVeaKpf5nTYmlxgT8OnKzwUb1dNd_gJSOYtrhLsE5yDfVJLrfzX-6aIjMruzNMZxCICaF6CgsYcTQhv8Gm5JeL3JqfAW8_-CwYKi3BB_PnnZsvbe2n2P9BG43YqZ73TvZBPWbgwoBlCaEg4diJb3cEpbE8d.tdbs5fA2Uw05O16EQxRgfQ

###
POST http://localhost:8081/jwt/logout
Authorization: Bearer eyJraWQiOiJjZTQ3YzUyYS0yN2QwLTRkMTktYjg3ZS03N2RlYjVmYmE5ZTUiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0YXJhc0BnbWFpbC5jb20iLCJleHAiOjE3MDkxMzY4NDUsImlhdCI6MTcwOTEzNjU0NSwianRpIjoiY2U0N2M1MmEtMjdkMC00ZDE5LWI4N2UtNzdkZWI1ZmJhOWU1IiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9NQU5BR0VSIiwiUk9MRV9VU0VSIl19.srUyLZHzcBf-Px6kQiSDjkZRaA7fuzpqncw391titvI


