spring:
  application:
    name: demo-app
  datasource:
    username: user123
    password: pass123
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
server:
  port: 8081

