spring:
  application:
    name: catalogue-service-flux
  datasource:
    username: user123
    password: pass123
    url: jdbc:postgresql://localhost:5432/catalog
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
server:
  port: 8084
logging:
  level:
    root: warn
    org.springframework.security: trace


