graphql:
  servlet:
    max-query-depth: 20
    exception-handlers-enabled: true
    tracing-enabled: true
  graphiql:
    enabled: true
  playground:
    enabled: true
  voyager:
    enabled: true
logging:
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %clr([%X{correlation_id}]){green} %m%n%wEx'
